first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.MyHomeView.as_view(), name='home'),
    path('student_list/', views.StudentListView.as_view(), name='student_list'),
    path('student_detail/<int:pk>/', views.StudentDetailView.as_view(), name='student_detail'),
    path('student_create/', views.StudentCreateView.as_view(), name='student_create'),
    path('student_update/<int:pk>', views.StudentUpdateView.as_view(), name='student_update'),
    path('student_delete/<int:pk>', views.StudentDeleteView.as_view(), name='student_delete'),

    path('teacher_list/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_create/', views.TeacherCreateView.as_view(), name='teacher_create'),

    path('subject_list/', views.SubjectListView.as_view(), name='subject_list'),
    path('subject_detail/<int:pk>/', views.SubjectDetailView.as_view(), name='subject_detail'),
    path('subject_create/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('subject_update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject_update'),
    path('subject_delete/<int:pk>', views.SubjectDeleteView.as_view(), name='subject_delete'),

]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('', RedirectView.as_view(url='first_app')), #redirect domain
]

first_app/models.py
from django.db import models
from django.contrib import admin


# Create your models here.
class Student(models.Model):
    """ Student database table """
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    weight = models.IntegerField()


class StudentAdmin(admin.ModelAdmin):
    list_filter = ['weight']

    def birthday(self, obj):
        """ Stackoverflow 7216764, 23086383 change date format on admin page"""
        if obj.date_of_birth is not None:
            return obj.date_of_birth.strftime('%d.%m.%Y')

    list_display = ['name', 'birthday', 'weight']
    list_per_page = 20


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name} teaches {self.subject}'


class TeacherAdmin(admin.ModelAdmin):

    list_display = ['name', 'subject']
    list_per_page = 10


class Subject(models.Model):
    subject = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.subject}'


class SubjectAdmin(admin.ModelAdmin):
    list_display = ['subject']

first_app/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView, UpdateView, DeleteView, )
from django.urls import reverse_lazy
from.models import Student, Teacher, Subject


# Create your views here.
class MyHomeView(TemplateView):
    template_name = 'first_app/home.html'


class StudentListView(ListView):
    # model_list.html -> student_ist.html
    model = Student  # Connected to Models Student
    queryset = Student.objects.order_by('name')  # Result ordered by name
    context_object_name = 'students'  # default object_list now students
    paginate_by = 10  # 10 per page in ListView


class StudentDetailView(DetailView):
    # Return only one model entry
    # default template model_detail.html => student_detail.html
    model = Student


class StudentCreateView(CreateView):
    template_name = 'first_app/student_form_create.html'
    model = Student
    fields = '__all__'  # All fields into form
    success_url = reverse_lazy('first_app:student_list')


class StudentUpdateView(UpdateView):
    # model_form.html => student_form.html
    model = Student
    fields = ['name', 'weight']  # update only this fields
    success_url = reverse_lazy('first_app:student_list')


class StudentDeleteView(DeleteView):
    # Form -> Confirm Delete Button
    # default template name => model_confirm_delete.html ->
    # -> student_confirm_delete.html
    model = Student
    # redirect after successful delete
    success_url = reverse_lazy('first_app:student_list')


class TeacherListView(ListView):

    model = Teacher  # Connected to Models Teacher
    queryset = Teacher.objects.order_by('name')  # Result ordered by name
    context_object_name = 'teacher'  # default object_list now teacher
    # paginate_by = 10  # 10 per page in ListView


class TeacherCreateView(CreateView):
    template_name = 'first_app/teacher_form_create.html'
    model = Teacher
    fields = '__all__'  # All fields into form
    success_url = reverse_lazy('first_app:teacher_list')


class SubjectListView(ListView):
    model = Subject
    queryset = Subject.objects.order_by('subject')  # Result ordered by name
    context_object_name = 'subject'  # default object_list now teacher


class SubjectCreateView(CreateView):
    template_name = 'first_app/subject_form_create.html'
    model = Subject
    fields = '__all__'  # All fields into form
    success_url = reverse_lazy('first_app:subject_list')


class SubjectDetailView(DetailView):
    model = Subject


class SubjectUpdateView(UpdateView):
    model = Subject
    fields = ['subject']  # update only this fields
    success_url = reverse_lazy('first_app:subject_list')


class SubjectDeleteView(DeleteView):
    model = Subject
    success_url = reverse_lazy('first_app:subject_list')

first_app/templates/first_app/home.html
{% extends 'base.html' %}
{% block content %}
    <h2>Homepage</h2>

    <h6>Student</h6>
    <p><a href="{% url 'first_app:student_list' %}">List All Students</a></p>
    <p><a href="{% url 'first_app:student_create' %}">Add a new Student</a></p>

    <h6>Teacher</h6>
    <p><a href="{% url 'first_app:teacher_list' %}">List All Teachers</a></p>
    <p><a href="{% url 'first_app:teacher_create' %}">Create New Teachers</a></p>

   <h6>Subject</h6>
    <p><a href="{% url 'first_app:subject_list' %}">List All Subjects</a></p>
    <p><a href="{% url 'first_app:subject_create' %}">Add a new Subjects</a></p>



{% endblock %}

first_app/templates/first_app/student_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
	<h4>Delete student "{{ student.name }}</h4>
    <form method="post">
        {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger">
    </form>
    <p></p>
    <p><a href="{% url 'first_app:student_list' %}">Student list</a></p>
{% endblock %}

first_app/templates/first_app/student_detail.html
{% extends 'base.html' %}
{% block content %}
	<h1>Detail view for student</h1>
    <div>
        <p>Full name: {{ student.name|upper }}</p>
        <p>Date: {{ student.date_of_birth|date:'d.m.Y' }} ->{{ student.date_of_birth }}</p>
        <p>Weight: {{ student.weight }} kg.</p>
    </div>
    <p></p>
    <p><a href="/first_app/student_list">Student list</a></p>
{% endblock %}

first_app/templates/first_app/student_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update </h1>
    <p>{{ student.name }}</p>
    <form method="post">
        {% csrf_token  %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-success">
    </form>

    <p></p>


    <a href="{% url 'first_app:home' %}">Homepage</a>

{% endblock %}

first_app/templates/first_app/student_form_create.html
{% extends 'base.html' %}

{% block content %}
	<h1>Add a new student</h1>
    <form method="post">
            {%  csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Student" class="btn btn-primary">
    </form>

    <p><a href="/first_app/student_list">Student list</a></p>
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>
{% endblock %}

first_app/templates/first_app/student_list.html
{% extends 'base.html' %}
{% block content %}
	<h4>Students list</h4>
    <a href="{% url 'first_app:home' %}">Home page</a>
    <p></p>
    {# students form views.py context_object_name= #}
    <ul>
        {% for student in students %}
            <li>
                {{ student.name }}
                [<a href="/first_app/student_detail/{{ student.id }}">Detail</a>]
                [<a href="/first_app/student_update/{{ student.id }}" class="text-success">Update</a>]
                [<a href="/first_app/student_delete/{{ student.id }}" class="text-danger" onclick="confirm('are you sure?')">Delete</a>]

            </li>
        {% endfor %}
    </ul>
{% endblock %}

first_app/templates/first_app/subject_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
	<h4>Delete subject "{{ subject.subject }}</h4>
    <form method="post">
        {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger">
    </form>
    <p></p>
    <p><a href="{% url 'first_app:subject_list' %}">Subject list</a></p>
{% endblock %}

first_app/templates/first_app/subject_detail.html
{% extends 'base.html' %}
{% block content %}
	<h4>Detail view for subject</h4>
    <div>
        <p>Full name: {{ subject.subject|upper }}</p>

    </div>
    <p></p>
    <p><a href="/first_app/subject_list">Student list</a></p>
{% endblock %}

first_app/templates/first_app/subject_form.html
{% extends 'base.html' %}
{% block content %}
    <h4>Update </h4>
    <p>{{ subject.subject }}</p>
    <form method="post">
        {% csrf_token  %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-success">
    </form>

    <p></p>


    <a href="{% url 'first_app:home' %}">Homepage</a>

{% endblock %}

first_app/templates/first_app/subject_form_create.html
{% extends 'base.html' %}

{% block content %}
	<h4>Add a new subject</h4>
    <form method="post">
            {%  csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Subject" class="btn btn-primary">
    </form>

    <p><a href="/first_app/subject_list">Subject list</a></p>
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>
{% endblock %}

first_app/templates/first_app/subject_list.html
{% extends 'base.html' %}
{% block content %}
	<h4>Subject list</h4>
    <a href="{% url 'first_app:home' %}">Home page</a>
    <p></p>
    {# students form views.py context_object_name= #}
    <ul>
        {% for subject in object_list %}
            <li>
                {{ subject.subject }}
                [<a href="/first_app/subject_detail/{{ subject.id }}">Detail</a>]
                [<a href="/first_app/subject_update/{{ subject.id }}" class="text-success">Update</a>]
                [<a href="/first_app/subject_delete/{{ subject.id }}" class="text-danger" onclick="confirm('are you sure?')">Delete</a>]

            </li>
        {% endfor %}
    </ul>

    <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>

        {% endif %}


        <li class="page-link text-dark">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>

        {% if page_obj.has_next %}
             <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>

         <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
         </li>

        {% endif %}


  </ul>



{% endblock %}

first_app/templates/first_app/teacher_form_create.html
{% extends 'base.html' %}

{% block content %}
	<h4>Add a new teacher</h4>
    <form method="post">
            {%  csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Teacher" class="btn btn-primary">
    </form>

    <p><a href="/first_app/teacher_list">Teacher list</a></p>
    <p><a href="{% url 'first_app:home' %}">Homepage</a></p>
{% endblock %}

first_app/templates/first_app/teacher_list.html
{% extends 'base.html' %}
{% block content %}
	<h4>Teacher list</h4>
    <a href="{% url 'first_app:home' %}">Home page</a>

    <p></p>

    <ul>
        {% for teacher in object_list %}
            <li>
                {{ teacher }}

            </li>
        {% endfor %}
    </ul>
    <p>There are {{ object_list|length }} teachers in total</p>

    <p></p>



 <a href="{% url 'first_app:teacher_create' %}">Lisa uus õpetaja</a>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base template</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</head>

<body>
    <!-- Comments -->
    {#  jinja comments #}
   <div class="container">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">

    <div class="container-fluid">
      <a class="navbar-brand" href="#"> <img width=50 height=50 src="https://logos-download.com/wp-content/uploads/2016/03/Starbucks_Logo_2011.png"/></a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'first_app:home' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teacher
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'first_app:teacher_list' %}">Õpetajate nimekiri</a></li>
            <li><a class="dropdown-item" href="{% url 'first_app:teacher_create' %}">Lisa uus õpetaja</a></li>

            <li><hr class="dropdown-divider"></li>

          </ul>
        </li>

           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Student
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'first_app:student_list' %}">Õpilaste list</a></li>
            <li><a class="dropdown-item" href="{% url 'first_app:student_create' %}">Lisa õpilane</a></li>

            <li><hr class="dropdown-divider"></li>

          </ul>
        </li>
           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Subject
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'first_app:subject_list' %}">Subject List</a></li>
            <li><a class="dropdown-item" href="{% url 'first_app:subject_create' %}">Add Subject</a></li>

            <li><hr class="dropdown-divider"></li>

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

        {% block content %}

        {% endblock %}
    </div>


</body>
</html>